<font size=6><b>lec01.NLP 텍스트 전처리(Text preprocessing)

<pre>
01) 토큰화(Tokenization)

02) 정제(Cleaning) and 정규화(Normalization)
03) 어간 추출(Stemming) and 표제어 추출(Lemmatization)
04) 불용어(Stopword)
05) 정규 표현식(Regular Expression)

06) 정수 인코딩(Integer Encoding)
08) 원-핫 인코딩(One-Hot Encoding)
07) 패딩(Padding)

* 딥 러닝을 이용한 자연어 처리 입문
* https://wikidocs.net/book/2155

* 자연어 처리(Natural Language Processing:NLP)
    * 자연어의 의미를 분석하여 컴퓨터가 처리할 수 있도록 하는 일

In [2]:
# ! pip install nltk
# ! pip install jpype    #---비추 (whl 다운받아 설치, JAVA_HOME\bin 환경변수)
# # -------------------- kkoma tweepy   (4)
# ! pip install konlpy   #---비추 (whl 다운받아 설치, tweepy==3.1x)
# # -------------------- 별도 한글 사전, 형태소 분석기 설치
# ! pip install mecab    #---비추 (whl 다운받아 설치, c:\mecab 압축풀기:x86,dic)

# # -------------------- 기타(띄어쓰기, PyKoSpacing:다운그래이드문제로 설치 XXX)
# ! pip install kss
# # -------------------- 기타(신조어)
# ! pip install soynlp


# 토큰화(Tokenization)
* 코퍼스(corpus)에서 토큰(token)이라 불리는 단위로 나누는 작업
* 단어 토큰화 : 일반적으로 whitespace(띄어쓰기)로 나눔
* 문장 토큰화 : 일반적으로 구두점(.)로 나눔


## nltk

### 단어 토큰화

In [6]:
# import nltk
# nltk.download('punkt')

<pre>
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\677\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

In [8]:
from nltk.tokenize import word_tokenize
# from nltk.tokenize import WordPunctTokenizer
# from nltk.tokenize import TreebankWordTokenizer

sent = "Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."

print('원본 :',sent)
print('단어 토큰화1 :',word_tokenize(sent))

원본 : Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop.
단어 토큰화1 : ['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


### 문장 토큰화

In [10]:
from nltk.tokenize import sent_tokenize

sent = """His barber kept his word. 
          But keeping such a huge secret to himself was driving him crazy. 
          Finally, the barber went up a mountain and almost to the edge of a cliff. 
          He dug a hole in the midst of some reeds. He looked about, to make sure no one was near."""

print('문장 토큰화 list :',sent_tokenize(sent))

문장 토큰화 list : ['His barber kept his word.', 'But keeping such a huge secret to himself was driving him crazy.', 'Finally, the barber went up a mountain and almost to the edge of a cliff.', 'He dug a hole in the midst of some reeds.', 'He looked about, to make sure no one was near.']


In [62]:
sent = "IP 192.168.56.31 서버에 들어가서 로그 파일 저장해서 aaa@gmail.com로 결과 좀. 보내줘. 그 후 점심 먹으러 가자."
print(' 문장 토큰화 list :',sent_tokenize(sent))

 문장 토큰화 list : ['IP 192.168.56.31 서버에 들어가서 로그 파일 저장해서 aaa@gmail.com로 결과 좀.', '보내줘.', '그 후 점심 먹으러 가자.']


In [16]:
# 줄바꿈하면 문장 분리가 안된다.
# import kss

# sent = """딥 러닝 자연어 처리가 재미있기는 합니다. 그런데 문제는 영어보다 한국어로 할 때 너무 어렵습니다! 이제 해보면 알걸요?"""
# print('한국어 문장 토큰화 :',kss.split_sentences(sent))

### 품사 태깅

In [19]:
# import nltk
# nltk.download('averaged_perceptron_tagger')

<pre>
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\677\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.

In [20]:
from nltk.tag import pos_tag

sent = "I am actively looking for Ph.D. students. and you are a Ph.D. student."
word_list = word_tokenize(sent)

print('단어 토큰화 :', word_list)
print('품사 태깅 :'  , pos_tag(word_list))

단어 토큰화 : ['I', 'am', 'actively', 'looking', 'for', 'Ph.D.', 'students', '.', 'and', 'you', 'are', 'a', 'Ph.D.', 'student', '.']
품사 태깅 : [('I', 'PRP'), ('am', 'VBP'), ('actively', 'RB'), ('looking', 'VBG'), ('for', 'IN'), ('Ph.D.', 'NNP'), ('students', 'NNS'), ('.', '.'), ('and', 'CC'), ('you', 'PRP'), ('are', 'VBP'), ('a', 'DT'), ('Ph.D.', 'NNP'), ('student', 'NN'), ('.', '.')]


## KoNLPy(코엔엘파이)

* 한국어 자연어 처리를 위한 파이썬 패키지
* 형태소 분석기 :  Okt(Open Korea Text), 코모란(Komoran), 한나눔(Hannanum), 꼬꼬마(Kkma)
* 메캅(Mecab) 별도 설치
    * 1) morphs : 형태소 추출
    * 2) pos : 품사 태깅(Part-of-speech tagging)
    * 3) nouns : 명사 추출


In [21]:
from konlpy.tag import Komoran
# from konlpy.tag import Okt
# from konlpy.tag import Kkma

komoran = Komoran()
# okt = Okt()
# kkma = Kkma()

print('Komoran 형태소 분석 :', komoran.morphs("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))

print('Komoran 품사 태깅 :'  , komoran.pos("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
print('Komoran 명사 추출 :'  , komoran.nouns("열심히 코딩한 당신, 연휴에는 여행을 가봐요")) 

Komoran 형태소 분석 : ['열심히', '코', '딩', '하', 'ㄴ', '당신', ',', '연휴', '에', '는', '여행', '을', '가', '아', '보', '아요']
Komoran 품사 태깅 : [('열심히', 'MAG'), ('코', 'NNG'), ('딩', 'MAG'), ('하', 'XSV'), ('ㄴ', 'ETM'), ('당신', 'NNP'), (',', 'SP'), ('연휴', 'NNG'), ('에', 'JKB'), ('는', 'JX'), ('여행', 'NNG'), ('을', 'JKO'), ('가', 'VV'), ('아', 'EC'), ('보', 'VX'), ('아요', 'EC')]
Komoran 명사 추출 : ['코', '당신', '연휴', '여행']


In [87]:
from nltk.tokenize import word_tokenize
sent = "열심히 코딩한 당신, 연휴에는 여행을 가봐요"
print('원본 :',sent)
print('단어 토큰화1 :',word_tokenize(sent))

원본 : 열심히 코딩한 당신, 연휴에는 여행을 가봐요
단어 토큰화1 : ['열심히', '코딩한', '당신', ',', '연휴에는', '여행을', '가봐요']


## Mecab : 한글 강추
* 사용법은 KoNLPy(코엔엘파이)와 같다

In [23]:
# --------------------------------
# Mecab 사전
# --------------------------------
from konlpy.tag import Mecab
mecab = Mecab(dicpath=r"C:\mecab\mecab-ko-dic")

print('Mecab 형태소 분석 :', mecab.morphs("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))

print('Mecab 품사 태깅 :'  , mecab.pos("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
print('Mecab 명사 추출 :'  , mecab.nouns("열심히 코딩한 당신, 연휴에는 여행을 가봐요")) 


Mecab 형태소 분석 : ['열심히', '코딩', '한', '당신', ',', '연휴', '에', '는', '여행', '을', '가', '봐요']
Mecab 품사 태깅 : [('열심히', 'MAG'), ('코딩', 'NNG'), ('한', 'XSA+ETM'), ('당신', 'NP'), (',', 'SC'), ('연휴', 'NNG'), ('에', 'JKB'), ('는', 'JX'), ('여행', 'NNG'), ('을', 'JKO'), ('가', 'VV'), ('봐요', 'EC+VX+EC')]
Mecab 명사 추출 : ['코딩', '당신', '연휴', '여행']


* 띄어쓰기에 민감하지 않다

In [25]:
print( mecab.morphs("아버지가방에들어가신다") )
print(  mecab.pos("아버지가방에들어가신다") )

['아버지', '가', '방', '에', '들어가', '신다']
[('아버지', 'NNG'), ('가', 'JKS'), ('방', 'NNG'), ('에', 'JKB'), ('들어가', 'VV'), ('신다', 'EP+EC')]


## keras

In [99]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence

In [100]:
print('Keras 토큰화 :', text_to_word_sequence("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))

Keras 토큰화 : ['열심히', '코딩한', '당신', '연휴에는', '여행을', '가봐요']


In [101]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [102]:
text = ["홍길동은 딥러닝을 공부한다."
        "홍길동은 딥러닝이 어렵다."
        "아무개도 딥러닝을 시작합니다."]
token = Tokenizer()
token.fit_on_texts(text)

In [104]:
print(f"문서카운트 : {token.document_count}")

문서카운트 : 1


In [105]:
print(f"워드카운트(빈도) : {token.word_counts}")

문서카운트 : OrderedDict([('홍길동은', 2), ('딥러닝을', 2), ('공부한다', 1), ('딥러닝이', 1), ('어렵다', 1), ('아무개도', 1), ('시작합니다', 1)])


In [107]:
print(f"워드에 인덱스 적용 : {token.texts_to_sequences(text)}")

워드에 인덱스 적용 : [[1, 2, 3, 1, 4, 5, 6, 2, 7]]


In [110]:
print(f"문서내 워드 출현 빈도 : {token.word_docs}")

문서내 워드 출현 빈도 : defaultdict(<class 'int'>, {'아무개도': 1, '시작합니다': 1, '어렵다': 1, '공부한다': 1, '딥러닝을': 1, '홍길동은': 1, '딥러닝이': 1})


In [111]:
text_seq_list = token.texts_to_sequences(text)
for seq, sent in zip (text_seq_list,text) :
    print(sent, seq)

홍길동은 딥러닝을 공부한다.홍길동은 딥러닝이 어렵다.아무개도 딥러닝을 시작합니다. [1, 2, 3, 1, 4, 5, 6, 2, 7]


# 전처리

## 정제(Cleaning), 정규화(Normalization)

* 정제(cleaning) : 갖고 있는 코퍼스로부터 노이즈 데이터를 제거한다.
    * 불용어
* 정규화(normalization) : 표현 방법이 다른 단어들을 통합시켜서 같은 단어로 만들어준다.
    * 어간(Stemming),표제어(Lemmatization) 추출
    * 정규성 : 단어수 == 피쳐수 (복잡성을 줄이는 일)
    * BoW(Bag of Words) : 단어의 빈도수를 기반 문서 내의 단어 수를 줄인다

## 어간(Stemming),표제어(Lemmatization) 추출

<pre>
* 표제어(Lemma) : '표제어' 또는 '기본 사전형 단어' 
* 어간(Stem)    : 어간(stem)과 접사(affix) 중 어간 추출
                : 단어의 의미를 담고 있는 단어의 핵심 부분
                
Lemmatization
    am → be
    the going → the going
    having → have

Stemming
    am → am
    the going → the go
    having → hav

### nltk

#### 표제어(Lemmatization) 추출

In [30]:
# import nltk
# nltk.download('wordnet')

<pre>
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\677\AppData\Roaming\nltk_data...

In [33]:
# import nltk
# nltk.download('omw-1.4')

<pre>
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\677\AppData\Roaming\nltk_data...

In [35]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

words = ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']

#------------ 'lives' -->  'life'  -------
print('표제어 추출 전 :',words)
print('표제어 추출 후 :',[lemmatizer.lemmatize(word) for word in words])

표제어 추출 전 : ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
표제어 추출 후 : ['policy', 'doing', 'organization', 'have', 'going', 'love', 'life', 'fly', 'dy', 'watched', 'ha', 'starting']


In [36]:
lemmatizer.lemmatize('has', 'v')

'have'

#### 어간(Stemming)

In [39]:
from nltk.stem import PorterStemmer
# from nltk.stem import LancasterStemmer

stemmer = PorterStemmer()
sent = "This was formalize allowance electricical."
word_list = word_tokenize(sent)

print('어간 추출 전 :', word_list)
print('어간 추출 후 :',[stemmer.stem(word) for word in word_list])

어간 추출 전 : ['This', 'was', 'formalize', 'allowance', 'electricical', '.']
어간 추출 후 : ['thi', 'wa', 'formal', 'allow', 'electric', '.']


In [90]:
from nltk.stem import PorterStemmer
# from nltk.stem import LancasterStemmer

stemmer = PorterStemmer()
sent = "나는 빨간 사과가 좋아지려고 합니다."
word_list = word_tokenize(sent)

print('어간 추출 전 :', word_list)
print('어간 추출 후 :',[stemmer.stem(word) for word in word_list])

어간 추출 전 : ['나는', '빨간', '사과가', '좋아지려고', '합니다', '.']
어간 추출 후 : ['나는', '빨간', '사과가', '좋아지려고', '합니다', '.']


### Konlpy
<pre>
* 용언(동사, 형용사)에 주로 활용
* 잡/어간 + 다/어미

* 어간(stem) 
    원칙적으로 모양이 변하지 않는 부분
    때론 어간의 모양도 바뀔 수 있음(예: 긋다, 긋고, 그어서, 그어라).
* 어미(ending)
    어간 뒤에 붙어서 활용하면서 변하는 부분
    여러 문법적 기능을 수행

In [98]:
from konlpy.tag import Okt
okt = Okt()
sent = "나는 빨간 사과가 좋아지려고 합니다."
print( okt.morphs(sent, norm=True, stem=True) )

['나', '는', '빨갛다', '사과', '가', '좋아지다', '하다', '.']


## 불용어(Stopword)
* 자주 등장하지만 분석을 하는 것에 있어서는 큰 도움이 되지 않는 단어들  
    ref : https://github.com/stopwords-iso/stopwords-ko  
    ./ko_stopwords.txt  
* 1차 : 불용어사전(csv, txt)을 이용
* 2차 : 최빈도(적다,많다) 제거
* 3차 : 정규화(import re)를 통해 제거

### nltk

In [42]:
# import nltk
# nltk.download('stopwords')

<pre>
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\677\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

In [43]:
from nltk.corpus import stopwords
stop_words_list = stopwords.words('english')
print('불용어 개수 :', len(stop_words_list))
print('불용어 10개 출력 :',stop_words_list[:10])

불용어 개수 : 179
불용어 10개 출력 : ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]


* 원리이해용

In [47]:
# stop_words_list.append("important")

# sent = "Apple is not an important thing. It's everything."
# word_list = word_tokenize(sent)

# result = []
# for word in word_list: 
#     if word not in stop_words_list: #씨잘데기없는게 아니면
#         result.append(word) 

# print('불용어 제거 전 :', sent) 
# print('불용어 제거 후 :', result)

# --------------------------------------
# 불용어 제거 전 : Apple is not an important thing. It's everything.
# 불용어 제거 후 : ['Apple', 'thing', '.', 'It', "'s", 'everything', '.']


### Mecap

In [55]:
sent = "고기를 아무렇게나 구우려고 하면 안 돼. 고기라고 다 같은 게 아니거든다."
stop_word_list = ["고기", "하면","안","돼","다"]

# -----------------------------------------------
# from konlpy.tag import Komoran
# komoran = Komoran()
# word_list = komoran.morphs(sent)  #형태소분석
# -----------------------------------------------

from konlpy.tag import Mecab
mecab = Mecab(dicpath=r"C:\mecab\mecab-ko-dic")
word_list = mecab.morphs(sent)  #형태소분석

result = [word for word in word_list if not word in stop_word_list]
# result = []
# for word in word_list: 
#     if word not in stop_words_list: #씨잘데기없는게 아니면
#         result.append(word) 

print('불용어 제거 전 :' ,sent) 
print('불용어 제거 후 :' ,result)

불용어 제거 전 : 고기를 아무렇게나 구우려고 하면 안 돼. 고기라고 다 같은 게 아니거든다.
불용어 제거 후 : ['를', '아무렇', '게', '나', '구우', '려고', '하', '면', '.', '라고', '같', '은', '게', '아니', '거든', '.']


# 인코딩

## 단어인덱스(voca)

In [113]:
from collections import Counter

In [115]:
sent = "나는 빨간 사과가 사과가 좋아지려고 합니다."
word_list = word_tokenize(sent)
vocab = Counter(word_list)
print(vocab)

Counter({'사과가': 2, '나는': 1, '빨간': 1, '좋아지려고': 1, '합니다': 1, '.': 1})


In [119]:
from tensorflow.keras.preprocessing.text import Tokenizer
sent = ["나는 빨간 사과가 사과가 좋아지려고 합니다."]  #---- 리스트타입
token = Tokenizer()
token.fit_on_texts(sent)     #---- fit_on_texts()
print(f"워드에 인덱스 적용 : {token.texts_to_sequences(sent)}")

워드에 인덱스 적용 : [[2, 3, 1, 1, 4, 5]]


In [120]:
print(token.word_index)  #--- voca

{'사과가': 1, '나는': 2, '빨간': 3, '좋아지려고': 4, '합니다': 5}


## 원핫 인코딩

### sklearn

In [167]:
from sklearn.preprocessing import OneHotEncoder
from tensorflow.keras.preprocessing.text import text_to_word_sequence
import pandas as pd
import numpy as np

oh = OneHotEncoder(sparse=False)
sent= '나는 빨간 사과가 사과가 좋아지려고 합니다.'
df = pd.DataFrame({'onehot':text_to_word_sequence(sent)})



temp = df["onehot"].values.reshape(-1,1)

oh.fit(temp)  #----------------------------리턴이 없다 주의주의주의주의
oh_res = oh.transform(temp)
ohdf = pd.DataFrame(oh_res,  columns=oh.categories_[0])
ohdf = pd.concat([df['onehot'],  ohdf], axis=1)

token = Tokenizer()
token.fit_on_texts([sent])   
print(token.texts_to_sequences([sent])[0])
ohdf["word_idx"] = token.texts_to_sequences([sent])[0]

ohdf.head(10)


[2, 3, 1, 1, 4, 5]


onehot   나는   빨간  사과가  좋아지려고  합니다  word_idx
0     나는  1.0  0.0  0.0    0.0  0.0         2
1     빨간  0.0  1.0  0.0    0.0  0.0         3
2    사과가  0.0  0.0  1.0    0.0  0.0         1
3    사과가  0.0  0.0  1.0    0.0  0.0         1
4  좋아지려고  0.0  0.0  0.0    1.0  0.0         4
5    합니다  0.0  0.0  0.0    0.0  1.0         5

In [174]:

oh = OneHotEncoder(sparse=False)
sent= ['나는 빨간 사과가 사과가 좋아지려고 합니다.','사과가 빨갛다']

token = Tokenizer()
token.fit_on_texts(sent)   
voca = token.word_index
print(voca)

encoding = token.texts_to_sequences(sent)
print(encoding)

max_len = max(len(item) for item in encoding)
print('최대 길이 :',max_len)

{'사과가': 1, '나는': 2, '빨간': 3, '좋아지려고': 4, '합니다': 5, '빨갛다': 6}
[[2, 3, 1, 1, 4, 5], [1, 6]]
최대 길이 : 6


In [192]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded = pad_sequences(encoding, padding="post")  #padding="pre"
padded

array([[2, 3, 1, 1, 4, 5],
       [1, 6, 0, 0, 0, 0]])

In [193]:
df = pd.DataFrame(padded)
df.head()


0  1  2  3  4  5
0  2  3  1  1  4  5
1  1  6  0  0  0  0

In [196]:
from tensorflow.keras.utils import to_categorical
oh_arr = to_categorical(df.iloc[0])
print(oh_arr.shape)
print(oh_arr)
df = pd.DataFrame(oh_arr)
df.head()

(6, 6)
[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


0    1    2    3    4    5
0  0.0  0.0  1.0  0.0  0.0  0.0
1  0.0  0.0  0.0  1.0  0.0  0.0
2  0.0  1.0  0.0  0.0  0.0  0.0
3  0.0  1.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  1.0  0.0

In [191]:
oh = OneHotEncoder()
oh_arr = oh.fit_transform(df)  #----2D
print(oh_arr.shape)
print(oh_arr)
df = pd.DataFrame(oh_arr)
df.head()


(2, 12)
  (0, 1)	1.0
  (0, 2)	1.0
  (0, 5)	1.0
  (0, 7)	1.0
  (0, 9)	1.0
  (0, 11)	1.0
  (1, 0)	1.0
  (1, 3)	1.0
  (1, 4)	1.0
  (1, 6)	1.0
  (1, 8)	1.0
  (1, 10)	1.0


0
0    (0, 1)\t1.0\n  (0, 2)\t1.0\n  (0, 5)\t1.0\n ...
1    (0, 0)\t1.0\n  (0, 3)\t1.0\n  (0, 4)\t1.0\n ...